openapi: 3.0.0
info:
  version: 1.0.0
  title: Branch API-2
  x-ibm-name: branch-api-2
  description: Опси Branch API  для ведення довідника бренчів корпорації
servers:
  - url: /branch-api
x-ibm-configuration:
  properties:
    target-url:
      value: https://application-ac.1nxfv2nzml19.eu-de.codeengine.appdomain.cloud
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          chunked-uploads: true
          persistent-connection: true
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /branch/{corporateid}:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    put:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                title: branchid
                properties:
                  branchid:
                    title: id створеного branch
                    type: string
      summary: Створити branch для корпорації
      description: Створити branch для корпорації
      operationId: put_create_branch
      parameters:
        - name: corporateid
          in: path
          required: true
          schema:
            type: string
            title: id корпорації - власник branch
      requestBody:
        description: Параметри branch  для створення
        content:
          application/json:
            schema:
              title: структура реквізтів branch  для створення
              type: object
              properties:
                branch_name:
                  title: Назва branch
                  type: string
                branch_edrpo:
                  title: ідентифікаційний код
                  type: string
                branch_sign_certs:
                  title: Масив сертифікатів - підписантів
                  type: array
                branch_encrypt_certs:
                  title: Масив сертифікатів шифрування
                  type: array
                branch_adress:
                  title: Адреса branch
                  type: string
                branch_phone:
                  title: Контактний телефон branch
                  type: string
    delete:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    summary: Ведення довідника бренчів корпорації
    description: |-
      Ведення довідника бренчів корпорації
      - Створити branch
      - Отримати дані branch корпорації
      - Отримати список всых branch корпорації
      - Видалити один branch  корпорації
