openapi: 3.0.0
info:
  version: 1.0.0
  title: Corporate APi
  x-ibm-name: corporate-api
  description: Ведення списку корпорацій
servers:
  - url: /corporate-api
x-ibm-configuration:
  properties:
    target-url:
      description: URL of the proxy policy f
      encoded: false
      value: >-
        https://application-f9.1nxfv2nzml19.eu-de.codeengine.appdomain.cloud/corporate
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          version: 2.3.0
          title: invoke
          backend-type: json
          header-control:
            type: blocklist
            values: []
          parameter-control:
            type: allowlist
            values: []
          http-version: HTTP/1.0
          timeout: 60
          verb: keep
          chunked-uploads: true
          persistent-connection: true
          cache-response: protocol
          cache-ttl: 900
          stop-on-error: []
          websocket-upgrade: false
          target-url: $(target-url)
    catch: []
  activity-log:
    enabled: true
    success-content: header
    error-content: header
  cors:
    enabled: false
paths:
  /corporate:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
      parameters: []
      requestBody:
        content: {}
    put:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                title: ID копорації
                properties:
                  corporateid:
                    title: id корпорації
                    type: string
      tags:
        - NewCortorate
      summary: Опис реквізитів нової корпорації
      description: Опис реквізитів нової корпорації для додавання
      operationId: put_corporate
      requestBody:
        content:
          application/json:
            schema:
              title: Структура для ддавання нової корпорації
              type: object
              properties:
                name:
                  title: Назва корпоарції
                  type: string
                edrpou:
                  title: Ідентифікаційни код
                  type: string
                contacts:
                  title: Контакти
                  type: string
    delete:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    options:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
