openapi: 3.0.0
info:
  version: 1.0.0
  title: ExtBranchAPI- Branch dict
  x-ibm-name: extbranchapi-branch-dict
  description: Опси Branch API  для ведення довідника бренчів корпорації
servers:
  - url: /extbranchapi
x-ibm-configuration:
  properties:
    target-url:
      value: https://application-f9.1nxfv2nzml19.eu-de.codeengine.appdomain.cloud
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          chunked-uploads: true
          persistent-connection: true
paths:
  /branch-api/branch:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
        5XX:
          description: Application Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        4XX:
          description: Application Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: get_branch_list
    put:
      operationId: put_create_branch
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  branch_name:
                    type: string
                  branch_erdpou:
                    type: string
                  branch_adress:
                    type: string
                  branch_phone:
                    type: string
                  branch_sign_certs:
                    type: array
                  branch_encrypt_certs:
                    type: array
        5XX:
          description: Application Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        4XX:
          description: Application Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    options:
      responses:
        '200':
          description: success
      operationId: option_branches
  /branch-api/branch/:corporateid/:branchid:
    get:
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  _rev:
                    type: string
                  type:
                    type: string
                  branch_name:
                    type: string
                  branch_erdpou:
                    type: string
                  branch_adress:
                    type: string
                  branch_phone:
                    type: string
                  branch_sign_certs:
                    type: array
                  branch_encrypt_certs:
                    type: array
        4XX:
          description: Application error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Application error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: get_branch_by_ids
      parameters:
        - name: corporateid
          in: path
          required: true
          schema:
            type: string
        - name: branchid
          in: path
          required: true
          schema:
            type: string
    options:
      responses:
        '200':
          description: success
      operationId: optons_branch_by_ids
      parameters:
        - name: corporateid
          in: path
          required: true
          schema:
            type: string
        - name: branchid
          in: path
          required: true
          schema:
            type: string
    delete:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  rev:
                    type: string
                  ok:
                    type: string
        5XX:
          description: Application Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        4XX:
          description: Application Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: delete_branch_by_ids
components:
  responses: {}
  schemas:
    InnerErrorType:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        stack:
          type: string
    ErrorType:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        target:
          type: string
        Inner:
          $ref: '#/components/schemas/InnerErrorType'
    Error:
      $ref: '#/components/schemas/ErrorType'
