openapi: 3.0.0
info:
  version: 1.0.0
  title: ExtCorporateAPI
  x-ibm-name: extcorporateapi
  description: Cotporate small 2
servers:
  - url: /extcorporateapi
x-ibm-configuration:
  properties:
    target-url:
      value: https://application-f9.1nxfv2nzml19.eu-de.codeengine.appdomain.cloud
      description: URL of the proxy policy
      encoded: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - operation-switch:
          version: 2.0.0
          title: operation-switch
          case:
            - operations:
                - get_corporate_list
              execute:
                - invoke:
                    version: 2.3.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    websocket-upgrade: false
                    graphql-send-type: detect
                    target-url: $(target-url)$(api.operation.path)
            - operations:
                - put_corporate
              execute:
                - invoke:
                    version: 2.0.0
                    title: invoke
                    backend-type: json
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    target-url: $(target-url)$(api.operation.path)
                    follow-redirects: false
                    inject-proxy-headers: true
            - operations:
                - get_corporate_by_id
              execute:
                - invoke:
                    version: 2.3.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    websocket-upgrade: false
                    graphql-send-type: detect
                    target-url: $(target-url)$(api.operation.path)
            - operations:
                - delete_corporation_by_id
              execute:
                - invoke:
                    version: 2.3.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    websocket-upgrade: false
                    graphql-send-type: detect
                    target-url: $(target-url)$(api.operation.path)
            - operations:
                - option_corporate_by_id
              execute:
                - invoke:
                    version: 2.3.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    websocket-upgrade: false
                    graphql-send-type: detect
                    target-url: $(target-url)$(api.operation.path)
            - operations:
                - option_corporate
              execute:
                - invoke:
                    version: 2.3.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    websocket-upgrade: false
                    graphql-send-type: detect
                    target-url: $(target-url)$(api.operation.path)
          otherwise: []
    catch: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
  cors:
    enabled: true
    policy: []
paths:
  /corporate-api/corporate:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                title: corporate array
                properties: {}
      operationId: get_corporate_list
    put:
      responses:
        '200':
          description: success
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  corporateid:
                    type: string
      operationId: put_corporate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                edrpou:
                  type: string
                contacts:
                  type: string
            examples: {}
    options:
      responses:
        '200':
          description: success
      operationId: option_corporate
      parameters: []
  /corporate-api/corporate/{corporateid}:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  _rev:
                    type: string
                  type:
                    type: string
                  name:
                    type: string
                  contacts:
                    type: string
                  branches:
                    type: array
      operationId: get_corporate_by_id
      parameters:
        - name: corporateid
          in: path
          required: true
          schema:
            type: string
    delete:
      responses:
        '200':
          description: success
      operationId: delete_corporation_by_id
      parameters:
        - name: corporateid
          in: path
          required: true
          schema:
            type: string
    options:
      responses:
        '200':
          description: success
      operationId: option_corporate_by_id
      parameters:
        - name: corporateid
          in: path
          required: true
          schema:
            type: string
